---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pr
  name: react-presensi
spec:
  selector:
    matchLabels:
      run: react-presensi
  replicas: 1
  template:
    metadata:
      labels:
        run: react-presensi
    spec:
      containers:
        - name: react-presensi
          image: registry.carakan.id/belajar/sudobash/react-presensi:v0.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-carakan
---
apiVersion: v1
kind: Service
metadata:
  namespace: pr
  name: react-presensi-service
spec:
  type: NodePort
  selector:
    run: react-presensi
  ports:
    - port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-react-presensi
  namespace: pr
spec:
  rules:
    - host: pr.bt66tech.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-presensi-service
                port:
                  number: 80
  ingressClassName: nginx
